version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      # Set the Keycloak admin username and password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      
      # Database configuration
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      
      # Optional: Set a custom realm for Keycloak
      # KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm.json
      
    ports:
      - "8055:8080"
    command: ["start-dev"]
