
server.port: 8000

#spring configs
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
            - POST
            - GET
            - OPTIONS
            allowedHeaders:
            - "Origin"
            - "Content-Type"
            - "Accept"
            - "Authorization"
            - "Referer"
      routes:
      - id: security-service
        uri: lb://security-service  # Load-balanced route to Service Two
        predicates:
          - Path=/api/auth/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8055/realms/master
eureka:
  client:
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka